"""initial

Revision ID: d22814e3e6c5
Revises: 
Create Date: 2026-06-02 02:46:25.887325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd22814e3e6c5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('agent_conversation_summaries_ibfk_1', 'agent_conversation_summaries', type_='foreignkey')
    op.drop_table('agent_conversation_summaries')
    op.drop_constraint('operation_logs_ibfk_1', 'operation_logs', type_='foreignkey')
    op.drop_table('operation_logs')
    op.drop_constraint('audit_logs_ibfk_1', 'audit_logs', type_='foreignkey')
    op.drop_table('audit_logs')
    op.drop_constraint('memory_entries_ibfk_1', 'memory_entries', type_='foreignkey')
    op.drop_table('memory_entries')
    op.drop_constraint('agent_student_profiles_ibfk_1', 'agent_student_profiles', type_='foreignkey')
    op.drop_table('agent_student_profiles')
    op.drop_constraint('agent_growth_scores_ibfk_1', 'agent_growth_scores', type_='foreignkey')
    op.drop_table('agent_growth_scores')
    op.drop_constraint('agent_risk_alerts_ibfk_1', 'agent_risk_alerts', type_='foreignkey')
    op.drop_table('agent_risk_alerts')
    op.drop_constraint('agent_student_skills_ibfk_1', 'agent_student_skills', type_='foreignkey')
    op.drop_table('agent_student_skills')
    op.alter_column('campus_figures', 'category',
               existing_type=mysql.ENUM('STUDENT', 'TEACHER', 'ALUMNI'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('campus_figures', 'proofs',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='证明材料JSON',
               existing_nullable=True)
    op.alter_column('users', 'password_changed',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_comment='是否已修改过密码',
               existing_server_default=sa.text("'0'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_changed',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_comment='是否已修改过密码',
               existing_server_default=sa.text("'0'"))
    op.alter_column('campus_figures', 'proofs',
               existing_type=mysql.TEXT(),
               comment='证明材料JSON',
               existing_nullable=True)
    op.alter_column('campus_figures', 'category',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('STUDENT', 'TEACHER', 'ALUMNI'),
               existing_nullable=False)
    op.create_table('agent_student_skills',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('skill_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('skill_category', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('proficiency', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('source', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('agent_student_skills_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_agent_student_skills_user_id'), 'agent_student_skills', ['user_id'], unique=False)
    op.create_table('agent_risk_alerts',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('risk_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('risk_level', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('ai_analysis', mysql.TEXT(), nullable=True),
    sa.Column('trend', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('resolved_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('agent_risk_alerts_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_agent_risk_alerts_user_id'), 'agent_risk_alerts', ['user_id'], unique=False)
    op.create_table('agent_growth_scores',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('semester', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('practice_score', mysql.FLOAT(), nullable=False),
    sa.Column('innovation_score', mysql.FLOAT(), nullable=False),
    sa.Column('academic_score', mysql.FLOAT(), nullable=False),
    sa.Column('social_score', mysql.FLOAT(), nullable=False),
    sa.Column('comprehensive_score', mysql.FLOAT(), nullable=False),
    sa.Column('final_score', mysql.FLOAT(), nullable=False),
    sa.Column('calculated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('agent_growth_scores_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_agent_growth_scores_user_id'), 'agent_growth_scores', ['user_id'], unique=False)
    op.create_table('agent_student_profiles',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('grade', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('major', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('class_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('gender', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('agent_student_profiles_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_agent_student_profiles_user_id'), 'agent_student_profiles', ['user_id'], unique=True)
    op.create_index(op.f('ix_agent_student_profiles_student_id'), 'agent_student_profiles', ['student_id'], unique=True)
    op.create_table('memory_entries',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('category', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('source', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('confidence', mysql.FLOAT(), nullable=True),
    sa.Column('tags', mysql.JSON(), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('memory_entries_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_memory_entries_student_id'), 'memory_entries', ['student_id'], unique=False)
    op.create_index(op.f('ix_memory_entries_id'), 'memory_entries', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('actor_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('target_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('detail', mysql.TEXT(), nullable=True),
    sa.Column('ip_address', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('audit_logs_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_audit_logs_target_id'), 'audit_logs', ['target_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_table('operation_logs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('action', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('resource', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('resource_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('ip_address', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('user_agent', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('extra_data', mysql.JSON(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('operation_logs_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_operation_logs_user_id'), 'operation_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_operation_logs_resource'), 'operation_logs', ['resource'], unique=False)
    op.create_index(op.f('ix_operation_logs_id'), 'operation_logs', ['id'], unique=False)
    op.create_index(op.f('ix_operation_logs_created_at'), 'operation_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_operation_logs_action'), 'operation_logs', ['action'], unique=False)
    op.create_table('agent_conversation_summaries',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('summary_type', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('summary_content', mysql.TEXT(), nullable=False),
    sa.Column('emotional_state', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('keywords', mysql.JSON(), nullable=True),
    sa.Column('risk_hint', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('period_start', mysql.DATETIME(), nullable=True),
    sa.Column('period_end', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('agent_conversation_summaries_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_agent_conversation_summaries_user_id'), 'agent_conversation_summaries', ['user_id'], unique=False)
    # ### end Alembic commands ###
